# Basic complete applications
    plot_det()
    # print ("plot_det() finished \n")
    plot_grid_search_digits()
    # print ("plot_grid_search_digits() finished \n")
    plot_cv_digits()
    # print ("plot_cv_digits() finished \n")
    plot_feature_union()
    # print ("plot_feature_union() finished \n")
    plot_pca_vs_lda()
    # print ("plot_pca_vs_lda() finished \n")

    # Tree regression models
    tree_regression_depth_200()
    # print ("tree_regression_depth_200() finished \n")
    tree_regression_depth_150()
    # print ("tree_regression_depth_3() finished \n")
    tree_regression_depth_170()
    # print ("tree_regression_depth_4() finished \n")
    tree_regression_compare_2()
    # print ("tree_regression_compare_2() finished \n")
    tree_regression_compare_3()
    # print ("tree_regression_compare_3() finished \n")
    tree_regression_compare_4()
    # print ("tree_regression_compare_4() finished \n")

    # Linear regression models
    linear_regression()
    # print ("linear_regression() finished \n")
    
    # Random Forest regression models
    random_forest_regression()
    # print ("random_forest_regression() finished \n")
    random_forest_regression_compare_2()
    # print ("random_forest_regression_compare_2() finished \n")
    random_forest_regression_compare_3()
    # print ("random_forest_regression_compare_3() finished \n")
    random_forest_regression_compare_4()
    # print ("random_forest_regression_compare_4() finished \n")
    random_forest_regression_compare_5()
    # print ("random_forest_regression_compare_5() finished \n")

    # Ridge regression models
    ridge_regression()
    # print ("ridge_regression() finished \n")
    ridge_regression_compare_2()
    # print ("ridge_regression_compare_2() finished \n")
    ridge_regression_compare_3()
    # print ("ridge_regression_compare_3() finished \n")
    ridge_regression_compare_4()
    # print ("ridge_regression_compare_4() finished \n")

    # Lasso regression models
    lasso_regression()
    # print ("lasso_regression() finished \n")
    lasso_regression_compare_2()
    # print ("lasso_regression_compare_2() finished \n")
    lasso_regression_compare_3()
    # print ("lasso_regression_compare_3() finished \n")
    lasso_regression_compare_4()
    # print ("lasso_regression_compare_4() finished \n")
